changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: 新功能
      labels: [feature, enhancement]
    - title: 修复
      labels: [bug, fix]
    - title: 工程与文档
      labels: [ci, chore, documentation]
    - title: 其他变更
      labels: ['*']
