import { platform } from './platform';
import { useEffect, useState } from 'react';
import { type AutoSyncSettings } from './auto-sync';
import { api, errorText, workspace, type Conflict, type SyncConfig, type SyncState, type Vault } from './api';
const initial:SyncConfig={protocol:'https',url:'',branch:'main',username:'git'};
export function SyncPanel({ busy, run, onVault, onReload, onSync, syncRevision, autoSync, autoPaused, onAutoSync }: { busy:boolean; run:<T>(action:()=>Promise<T>)=>Promise<T|undefined>; onVault:(vault:Vault)=>Promise<void>; onReload:()=>Promise<void>; onSync:()=>Promise<void>; syncRevision:number; autoSync:AutoSyncSettings; autoPaused:boolean; onAutoSync:(settings:AutoSyncSettings)=>void }) {
  const [config,setConfig]=useState<SyncConfig>(initial),[state,setState]=useState<SyncState|null>(null),[message,setMessage]=useState(''),[name,setName]=useState('我的笔记'),[decisions,setDecisions]=useState<Record<string,{choice:string;content:string}>>({});
  useEffect(()=>{workspace<SyncConfig|null>({action:'config'}).then(c=>{if(c)setConfig({...c,protocol:c.protocol||'https'});}).catch(e=>setMessage(errorText(e)));workspace<SyncState>({action:'sync_state'}).then(setState).catch(e=>setMessage(errorText(e)));},[]);
  useEffect(()=>{let active=true;workspace<SyncState>({action:'sync_state'}).then(value=>{if(active)setState(value);}).catch(e=>{if(active)setMessage(errorText(e));});return()=>{active=false;};},[syncRevision]);
  async function syncNow(){setMessage('');await onSync();}
  async function resolve(){await run(async()=>{const result=await workspace<{state:SyncState}>({action:'resolve',decisions:Object.entries(decisions).map(([path,value])=>({path,...value}))});setState(result.state);setDecisions({});await onReload();});}
  function choose(c:Conflict,choice:string){setDecisions(d=>({...d,[c.path]:{choice,content:d[c.path]?.content??c.local??c.remote??''}}));}
  const ssh=config.protocol==='ssh';
  return <section className="lab-panel"><p className="eyebrow">YOUR NOTES, EVERYWHERE</p><h1>同步与恢复</h1><p className="subtle">每个笔记库使用固定分支。先保存本地内容，再获取、合并和推送。</p>
    <div className="settings-grid"><label>同步协议<select value={config.protocol} onChange={e=>setConfig({...config,protocol:e.target.value as SyncConfig['protocol'],url:''})}><option value="https">HTTPS</option><option value="ssh">SSH</option></select></label><label>{ssh?'SSH 仓库 URL':'HTTPS 仓库 URL'}<input value={config.url} onChange={e=>setConfig({...config,url:e.target.value})} placeholder={ssh?'ssh://git@github.com/you/notes.git':'https://github.com/you/notes.git'}/></label><label>分支<input value={config.branch} onChange={e=>setConfig({...config,branch:e.target.value})}/></label><label>{ssh?'SSH 用户名':'HTTPS 用户名'}<input value={config.username} onChange={e=>setConfig({...config,username:e.target.value})}/></label></div>
    {ssh&&<p className="subtle">SSH 使用系统 Agent，私钥和密码不保存在墨知中。{platform.desktop!=='macOS'&&'请先通过系统 ssh-add 加载私钥。'}</p>}
    <div className="workspace-toolbar"><button disabled={busy} onClick={()=>void run(async()=>{await workspace({action:'configure',config});setMessage('同步设置已保存');})}>保存设置</button>{ssh?<><button disabled={busy||platform.desktop!=='macOS'} onClick={()=>void run(async()=>{setMessage('');const result=await api.selectSshKey();setMessage(result?`SSH 密钥已加载，Agent 中有 ${result.keyCount} 把密钥`:'已取消选择 SSH 密钥');})}>选择 SSH 密钥</button><button disabled={busy||platform.desktop!=='macOS'} onClick={()=>void run(async()=>{setMessage('');const result=await api.checkSshAgent();setMessage(`SSH Agent 已连接，已加载 ${result.keyCount} 把密钥；仓库权限将在克隆或同步时验证`);})}>检查 SSH Agent</button></>:<button disabled={busy} onClick={()=>void run(async()=>{if(await api.credentials(config))setMessage(`凭据已保存至 ${platform.credentials}`);})}>设置 {platform.credentials} Token</button>}<button className="primary" disabled={busy||state?.phase==='conflict'} onClick={()=>void syncNow()}>立即同步</button></div>
    <section className="auto-sync-settings"><h2>自动同步</h2><label><input type="checkbox" disabled={busy} checked={autoSync.enabled} onChange={e=>onAutoSync({...autoSync,enabled:e.target.checked})}/>启用自动同步</label><div className="workspace-toolbar"><label><input type="checkbox" disabled={busy||!autoSync.enabled} checked={autoSync.onOpen} onChange={e=>onAutoSync({...autoSync,onOpen:e.target.checked})}/>打开笔记库时同步</label><label><input type="checkbox" disabled={busy||!autoSync.enabled} checked={autoSync.afterSave} onChange={e=>onAutoSync({...autoSync,afterSave:e.target.checked})}/>保存后空闲同步</label></div><div className="workspace-toolbar"><label>空闲时间（秒） <input aria-label="自动同步空闲时间" type="number" min={10} max={600} step={1} disabled={busy||!autoSync.enabled||!autoSync.afterSave} value={autoSync.idleSeconds} onChange={e=>{const value=Number(e.target.value);if(Number.isInteger(value)&&value>=10&&value<=600)onAutoSync({...autoSync,idleSeconds:value});}}/></label><label>同步间隔（分钟） <input aria-label="自动同步间隔" type="number" min={1} max={60} step={1} disabled={busy||!autoSync.enabled} value={autoSync.intervalMinutes} onChange={e=>{const value=Number(e.target.value);if(Number.isInteger(value)&&value>=1&&value<=60)onAutoSync({...autoSync,intervalMinutes:value});}}/></label></div>{autoSync.enabled&&autoPaused&&<p className="notice" role="status">自动同步已暂停，请处理错误或冲突后点击「立即同步」。</p>}</section>
    <div className="clone-section"><h2>克隆已有仓库</h2><p className="subtle">使用上方仓库和凭据，选择父目录后创建一个新的笔记库。</p><div className="workspace-toolbar"><input aria-label="克隆目录名称" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} onClick={()=>void run(async()=>{const vault=await api.clone(config,name);if(vault){await onVault(vault);setMessage('克隆完成');}})}>选择位置并克隆</button></div></div>
    {message&&<p className="notice" role="status">{message}</p>}{state&&<div className="acceptance-note"><h3>{state.phase==='conflict'?'需要处理冲突':state.phase==='error'?'同步未完成':'同步状态'}</h3><p>{state.message}{state.lastSuccess&&` · 上次成功 ${new Date(state.lastSuccess*1000).toLocaleString()}`}</p></div>}
    {state?.conflicts.map(c=><article className="conflict-card" key={c.path}><h2>{c.path}</h2><p className="subtle">{c.binary?'二进制附件冲突：可选择单方或保留双方；原引用继续使用本地版本，远程副本以 -remote-提交标识 命名。':'对照三个版本，选择或编辑最终内容。'}{c.localDeleted?' 本地已删除。':''}{c.remoteDeleted?' 远程已删除。':''}</p>{!c.binary&&<div className="three-way">{[['共同祖先',c.ancestor],['本地版本',c.local],['远程版本',c.remote]].map(([label,text])=><label key={label}>{label}<textarea readOnly value={text??'（不存在 / 已删除）'}/></label>)}</div>}<div className="workspace-toolbar"><button className={decisions[c.path]?.choice==='local'?'primary':''} onClick={()=>choose(c,'local')}>采用本地{c.localDeleted?'（删除）':''}</button><button className={decisions[c.path]?.choice==='remote'?'primary':''} onClick={()=>choose(c,'remote')}>采用远程{c.remoteDeleted?'（删除）':''}</button>{!c.binary&&<button onClick={()=>choose(c,'manual')}>手动合并</button>}{c.binary&&!c.localDeleted&&!c.remoteDeleted&&<button className={decisions[c.path]?.choice==='both'?'primary':''} onClick={()=>choose(c,'both')}>保留双方（原引用使用本地）</button>}</div>{decisions[c.path]?.choice==='manual'&&<textarea aria-label={`${c.path} 合并结果`} value={decisions[c.path].content} onChange={e=>setDecisions(d=>({...d,[c.path]:{choice:'manual',content:e.target.value}}))}/>}</article>)}
    {!!state?.conflicts.length&&<button disabled={busy||state.conflicts.some(c=>!decisions[c.path])} onClick={()=>void resolve()}>保存决议并提交</button>}
  </section>;
}
