[package]
name = "mozhi-windows"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
sha2 = "0.10"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security_Credentials", "Win32_Graphics_Gdi", "Win32_Storage_FileSystem", "Win32_System_Threading"] }

[dev-dependencies]
tempfile = "3"
